package org.example.util;

import java.util.regex.Pattern;

/**
 * Utility class for validating and cleaning commit messages generated by AI.
 * Handles common issues like empty responses, markdown artifacts, and formatting.
 */
public class MessageValidator {
    private static final int MAX_SUBJECT_LENGTH = 72;
    private static final int MAX_BODY_LINE_LENGTH = 72;

    // Patterns for markdown artifacts that should be removed
    private static final Pattern MARKDOWN_CODE_BLOCK = Pattern.compile("```[a-z]*\\n?|```");
    private static final Pattern MARKDOWN_BOLD = Pattern.compile("\\*\\*(.+?)\\*\\*");
    private static final Pattern MARKDOWN_ITALIC = Pattern.compile("\\*(.+?)\\*|_(.+?)_");
    private static final Pattern MARKDOWN_HEADERS = Pattern.compile("^#+\\s+", Pattern.MULTILINE);

    /**
     * Validates that the message is non-empty after trimming whitespace.
     *
     * @param message the message to validate
     * @return true if message is non-empty, false otherwise
     */
    public static boolean isNonEmpty(String message) {
        return message != null && !message.trim().isEmpty();
    }

    /**
     * Removes common markdown formatting artifacts from the message.
     * This includes code blocks, bold, italic, and headers.
     *
     * @param message the message to clean
     * @return cleaned message without markdown artifacts
     */
    public static String removeMarkdownArtifacts(String message) {
        if (message == null) {
            return "";
        }

        String cleaned = message;

        // Remove code block markers
        cleaned = MARKDOWN_CODE_BLOCK.matcher(cleaned).replaceAll("");

        // Remove bold formatting (keep content)
        cleaned = MARKDOWN_BOLD.matcher(cleaned).replaceAll("$1");

        // Remove italic formatting (keep content)
        cleaned = MARKDOWN_ITALIC.matcher(cleaned).replaceAll("$1$2");

        // Remove header markers
        cleaned = MARKDOWN_HEADERS.matcher(cleaned).replaceAll("");

        return cleaned;
    }

    /**
     * Ensures proper commit message formatting following best practices:
     * - First line (subject) should be <= 72 characters
     * - Blank line between subject and body
     * - Body lines wrapped at 72 characters
     *
     * @param message the message to format
     * @return properly formatted commit message
     */
    public static String ensureProperFormatting(String message) {
        if (message == null || message.trim().isEmpty()) {
            return "";
        }

        String[] lines = message.split("\n");
        StringBuilder formatted = new StringBuilder();

        // Process first line (subject)
        if (lines.length > 0) {
            String subject = lines[0].trim();
            if (subject.length() > MAX_SUBJECT_LENGTH) {
                subject = truncateLine(subject, MAX_SUBJECT_LENGTH);
            }
            formatted.append(subject);
        }

        // Process remaining lines (body)
        boolean inBody = false;
        for (int i = 1; i < lines.length; i++) {
            String line = lines[i].trim();

            // Skip empty lines at the start of body
            if (!inBody && line.isEmpty()) {
                continue;
            }

            // Add blank line before body starts
            if (!inBody && !line.isEmpty()) {
                formatted.append("\n\n");
                inBody = true;
            }

            // Add body line
            if (inBody) {
                if (line.isEmpty()) {
                    formatted.append("\n");
                } else {
                    // Wrap long lines
                    String wrapped = wrapLine(line, MAX_BODY_LINE_LENGTH);
                    formatted.append(wrapped);
                }
            }
        }

        return formatted.toString();
    }

    /**
     * Truncates a line to the specified maximum length, ensuring we don't break words.
     *
     * @param line the line to truncate
     * @param maxLength maximum length
     * @return truncated line
     */
    private static String truncateLine(String line, int maxLength) {
        if (line.length() <= maxLength) {
            return line;
        }

        // Try to truncate at a word boundary
        int lastSpace = line.lastIndexOf(' ', maxLength);
        if (lastSpace > maxLength / 2) {
            return line.substring(0, lastSpace);
        }

        // If no good word boundary, hard truncate
        return line.substring(0, maxLength);
    }

    /**
     * Wraps a line to the specified maximum length, preserving words.
     *
     * @param line the line to wrap
     * @param maxLength maximum line length
     * @return wrapped text with newlines
     */
    private static String wrapLine(String line, int maxLength) {
        if (line.length() <= maxLength) {
            return line + "\n";
        }

        StringBuilder wrapped = new StringBuilder();
        String remaining = line;

        while (remaining.length() > maxLength) {
            int breakPoint = remaining.lastIndexOf(' ', maxLength);

            if (breakPoint == -1 || breakPoint < maxLength / 2) {
                // No good break point found, hard break
                breakPoint = maxLength;
            }

            wrapped.append(remaining.substring(0, breakPoint).trim()).append("\n");
            remaining = remaining.substring(breakPoint).trim();
        }

        if (!remaining.isEmpty()) {
            wrapped.append(remaining).append("\n");
        }

        return wrapped.toString();
    }

    /**
     * Performs complete validation and cleanup of a commit message:
     * 1. Validates non-empty
     * 2. Removes markdown artifacts
     * 3. Ensures proper formatting
     * 4. Truncates if too long
     *
     * @param message the raw message from AI
     * @return cleaned and validated message
     * @throws IllegalArgumentException if message is empty after cleaning
     */
    public static String validateAndClean(String message) {
        // Step 1: Check if non-empty
        if (!isNonEmpty(message)) {
            throw new IllegalArgumentException("Generated commit message is empty");
        }

        // Step 2: Remove markdown artifacts
        String cleaned = removeMarkdownArtifacts(message);

        // Step 3: Trim whitespace
        cleaned = cleaned.trim();

        // Step 4: Check if still non-empty after cleaning
        if (cleaned.isEmpty()) {
            throw new IllegalArgumentException("Commit message is empty after removing markdown artifacts");
        }

        // Step 5: Ensure proper formatting and truncation
        cleaned = ensureProperFormatting(cleaned);

        return cleaned;
    }
}
